# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  PROD_FLAG: "--prod"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install NPM Dependencies
        run: npm install

      - name: Set Preview Deploy Flag
        if: github.event_name == 'pull_request'
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV

      - name: Deploy to Hosting Provider
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: ${{ env.PROD_FLAG }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-deployment: true
          vercel-org-id: ${{ secrets.NOW_ORG_ID}}
          vercel-project-id: ${{ secrets.NOW_PROJECT_ID}}
